import { CareerPath } from './types';

export const careerPaths: CareerPath[] = [
  {
    id: 'technology_engineering',
    title: 'Technology & Engineering',
    description:
      'Design, build, and maintain software systems, hardware, and digital infrastructure. Ideal for logical thinkers who enjoy problem-solving and creating technical solutions.',
    icon: '💻',
    weights: {
      technical_skills: { high: 2.0, medium: 1.2, low: 0.3 },
      creative_skills: { high: 0.8, medium: 0.6, low: 0.5 },
      communication_skills: { high: 0.6, medium: 0.6, low: 0.5 },
      enjoyed_skills: {
        problem_solving: 1.8,
        coding: 2.0,
        data_analysis: 1.5,
        research: 1.2,
        collaboration: 0.8,
      },
      work_energizes: {
        building: 2.0,
        optimizing: 1.5,
        analyzing: 1.3,
        learning: 1.5,
      },
      problem_type: {
        technical: 2.0,
        analytical: 1.5,
        creative: 0.8,
        business: 0.5,
        people: 0.3,
      },
      industry_interest: {
        technology_engineering: 2.0,
        science_research: 1.2,
        manufacturing_construction: 0.8,
      },
      work_environment: {
        startup: 1.5,
        corporate: 1.2,
        freelance: 1.2,
        agency: 0.8,
        consulting: 0.8,
        nonprofit: 0.5,
      },
      team_size: {
        solo: 1.2,
        small: 1.5,
        medium: 1.0,
        large: 0.8,
      },
      structure_preference: { low: 1.2, medium: 1.0, high: 0.8 },
    },
    suggestedSkills: [
      'Programming and software development',
      'System design and architecture',
      'Data structures and algorithms',
      'Cloud computing and DevOps',
      'Testing and quality assurance',
    ],
    exampleJobs: [
      'Software Engineer',
      'Data Engineer',
      'DevOps Engineer',
      'IT Support Specialist',
      'QA Engineer',
      'Systems Architect',
    ],
    resources: [
      { title: 'freeCodeCamp', url: 'https://www.freecodecamp.org/' },
      { title: 'The Odin Project', url: 'https://www.theodinproject.com/' },
      { title: 'Coursera Tech Courses', url: 'https://www.coursera.org/' },
    ],
  },
  {
    id: 'business_management',
    title: 'Business, Management & Strategy',
    description:
      'Lead teams, drive organizational strategy, and optimize business operations. Perfect for strategic thinkers who enjoy leadership and making impactful decisions.',
    icon: '📊',
    weights: {
      technical_skills: { high: 0.8, medium: 1.0, low: 0.8 },
      creative_skills: { high: 1.0, medium: 1.0, low: 0.6 },
      communication_skills: { high: 2.0, medium: 1.2, low: 0.4 },
      enjoyed_skills: {
        problem_solving: 1.5,
        leadership: 2.0,
        collaboration: 1.5,
        presenting: 1.5,
        negotiation: 1.8,
        data_analysis: 1.0,
      },
      work_energizes: {
        strategizing: 2.0,
        optimizing: 1.5,
        connecting: 1.5,
        helping: 1.0,
      },
      problem_type: {
        business: 2.0,
        people: 1.5,
        analytical: 1.2,
        technical: 0.6,
        creative: 0.6,
      },
      industry_interest: {
        business_management: 2.0,
        finance_accounting: 1.2,
        marketing_sales: 1.0,
      },
      work_environment: {
        corporate: 1.8,
        consulting: 1.5,
        startup: 1.2,
        nonprofit: 0.8,
        agency: 0.6,
        freelance: 0.5,
      },
      team_size: {
        medium: 1.8,
        large: 1.5,
        small: 1.0,
        solo: 0.3,
      },
      structure_preference: { low: 0.6, medium: 1.2, high: 1.5 },
    },
    suggestedSkills: [
      'Strategic planning and execution',
      'Team leadership and management',
      'Business analysis and operations',
      'Project management',
      'Stakeholder communication',
    ],
    exampleJobs: [
      'Product Manager',
      'Operations Manager',
      'Management Consultant',
      'Business Analyst',
      'Project Manager',
      'General Manager',
    ],
    resources: [
      { title: 'Harvard Business Review', url: 'https://hbr.org/' },
      { title: 'LinkedIn Learning Business', url: 'https://www.linkedin.com/learning/' },
      { title: 'Coursera Business Courses', url: 'https://www.coursera.org/browse/business' },
    ],
  },
  {
    id: 'finance_accounting',
    title: 'Finance & Accounting',
    description:
      'Manage financial resources, analyze investments, and ensure fiscal compliance. Ideal for detail-oriented individuals who enjoy numbers and financial analysis.',
    icon: '💰',
    weights: {
      technical_skills: { high: 1.5, medium: 1.2, low: 0.5 },
      creative_skills: { high: 0.4, medium: 0.6, low: 1.0 },
      communication_skills: { high: 1.2, medium: 1.0, low: 0.6 },
      enjoyed_skills: {
        data_analysis: 2.0,
        problem_solving: 1.5,
        research: 1.2,
        writing: 1.0,
        negotiation: 1.2,
      },
      work_energizes: {
        analyzing: 2.0,
        optimizing: 1.5,
        strategizing: 1.2,
        learning: 1.0,
      },
      problem_type: {
        analytical: 2.0,
        business: 1.5,
        technical: 1.0,
        people: 0.5,
        creative: 0.3,
      },
      industry_interest: {
        finance_accounting: 2.0,
        business_management: 1.2,
        law_government: 0.8,
      },
      work_environment: {
        corporate: 1.8,
        consulting: 1.5,
        startup: 0.8,
        freelance: 1.0,
        nonprofit: 0.6,
        agency: 0.4,
      },
      team_size: {
        small: 1.5,
        medium: 1.3,
        solo: 1.2,
        large: 1.0,
      },
      structure_preference: { low: 0.4, medium: 1.0, high: 2.0 },
    },
    suggestedSkills: [
      'Financial analysis and modeling',
      'Accounting principles (GAAP/IFRS)',
      'Excel and financial software',
      'Risk assessment',
      'Regulatory compliance',
    ],
    exampleJobs: [
      'Accountant',
      'Financial Analyst',
      'Investment Banker',
      'Auditor',
      'Tax Specialist',
      'CFO',
    ],
    resources: [
      { title: 'CFA Institute', url: 'https://www.cfainstitute.org/' },
      { title: 'Investopedia', url: 'https://www.investopedia.com/' },
      { title: 'Wall Street Prep', url: 'https://www.wallstreetprep.com/' },
    ],
  },
  {
    id: 'healthcare_life_sciences',
    title: 'Healthcare & Life Sciences',
    description:
      'Improve human health through medical care, research, and biotechnology. Perfect for those driven by helping others and advancing medical knowledge.',
    icon: '🏥',
    weights: {
      technical_skills: { high: 1.5, medium: 1.2, low: 0.8 },
      creative_skills: { high: 0.8, medium: 0.8, low: 0.8 },
      communication_skills: { high: 1.5, medium: 1.2, low: 0.6 },
      enjoyed_skills: {
        research: 2.0,
        problem_solving: 1.5,
        collaboration: 1.3,
        data_analysis: 1.2,
        writing: 1.0,
      },
      work_energizes: {
        helping: 2.0,
        analyzing: 1.5,
        learning: 1.5,
        building: 0.8,
      },
      problem_type: {
        analytical: 1.8,
        people: 1.5,
        technical: 1.2,
        business: 0.6,
        creative: 0.5,
      },
      industry_interest: {
        healthcare_life_sciences: 2.0,
        science_research: 1.5,
        social_impact_nonprofit: 1.0,
      },
      work_environment: {
        corporate: 1.2,
        nonprofit: 1.5,
        startup: 1.0,
        consulting: 0.8,
        agency: 0.3,
        freelance: 0.5,
      },
      team_size: {
        medium: 1.5,
        small: 1.3,
        large: 1.2,
        solo: 0.5,
      },
      structure_preference: { low: 0.5, medium: 1.2, high: 1.5 },
    },
    suggestedSkills: [
      'Medical/scientific knowledge',
      'Research methodology',
      'Patient care and communication',
      'Data analysis and statistics',
      'Regulatory compliance (FDA, HIPAA)',
    ],
    exampleJobs: [
      'Doctor/Physician',
      'Nurse',
      'Public Health Analyst',
      'Biomedical Scientist',
      'Clinical Research Coordinator',
      'Healthcare Administrator',
    ],
    resources: [
      { title: 'Khan Academy Medicine', url: 'https://www.khanacademy.org/science/health-and-medicine' },
      { title: 'Coursera Health Courses', url: 'https://www.coursera.org/browse/health' },
      { title: 'PubMed', url: 'https://pubmed.ncbi.nlm.nih.gov/' },
    ],
  },
  {
    id: 'education_training',
    title: 'Education & Training',
    description:
      'Shape minds and develop talent through teaching, curriculum design, and professional development. Ideal for patient communicators who love sharing knowledge.',
    icon: '📚',
    weights: {
      technical_skills: { high: 0.8, medium: 1.0, low: 1.0 },
      creative_skills: { high: 1.5, medium: 1.2, low: 0.6 },
      communication_skills: { high: 2.0, medium: 1.2, low: 0.4 },
      enjoyed_skills: {
        presenting: 2.0,
        writing: 1.5,
        collaboration: 1.3,
        research: 1.2,
        leadership: 1.0,
      },
      work_energizes: {
        helping: 2.0,
        creating: 1.5,
        connecting: 1.3,
        learning: 1.5,
      },
      problem_type: {
        people: 2.0,
        creative: 1.2,
        analytical: 0.8,
        business: 0.5,
        technical: 0.5,
      },
      industry_interest: {
        education_training: 2.0,
        social_impact_nonprofit: 1.3,
        healthcare_life_sciences: 0.6,
      },
      work_environment: {
        nonprofit: 1.8,
        corporate: 1.0,
        freelance: 1.2,
        startup: 0.8,
        consulting: 1.0,
        agency: 0.5,
      },
      team_size: {
        small: 1.5,
        medium: 1.3,
        solo: 1.2,
        large: 0.8,
      },
      structure_preference: { low: 1.0, medium: 1.5, high: 1.0 },
    },
    suggestedSkills: [
      'Curriculum design and development',
      'Public speaking and presentation',
      'Learning management systems',
      'Assessment and evaluation',
      'Educational technology',
    ],
    exampleJobs: [
      'Teacher',
      'University Lecturer',
      'Instructional Designer',
      'Corporate Trainer',
      'Education Consultant',
      'Academic Administrator',
    ],
    resources: [
      { title: 'Coursera Teaching Courses', url: 'https://www.coursera.org/browse/education' },
      { title: 'edX Education', url: 'https://www.edx.org/learn/education' },
      { title: 'ISTE', url: 'https://www.iste.org/' },
    ],
  },
  {
    id: 'creative_media_design',
    title: 'Creative, Media & Design',
    description:
      'Create compelling visual and written content across digital and traditional media. Perfect for artistic individuals who love expressing ideas through design and storytelling.',
    icon: '🎨',
    weights: {
      technical_skills: { high: 0.8, medium: 1.0, low: 1.0 },
      creative_skills: { high: 2.0, medium: 1.2, low: 0.3 },
      communication_skills: { high: 1.5, medium: 1.2, low: 0.6 },
      enjoyed_skills: {
        design: 2.0,
        writing: 1.8,
        presenting: 1.2,
        collaboration: 1.0,
        problem_solving: 1.0,
      },
      work_energizes: {
        creating: 2.0,
        building: 1.5,
        connecting: 1.0,
        helping: 0.8,
      },
      problem_type: {
        creative: 2.0,
        people: 1.2,
        business: 0.8,
        technical: 0.6,
        analytical: 0.5,
      },
      industry_interest: {
        creative_media_design: 2.0,
        marketing_sales: 1.2,
        technology_engineering: 0.8,
      },
      work_environment: {
        agency: 2.0,
        freelance: 1.8,
        startup: 1.5,
        corporate: 0.8,
        consulting: 0.6,
        nonprofit: 0.8,
      },
      team_size: {
        small: 1.8,
        solo: 1.5,
        medium: 1.0,
        large: 0.6,
      },
      structure_preference: { low: 1.8, medium: 1.0, high: 0.4 },
    },
    suggestedSkills: [
      'Visual design (UI/UX, graphic design)',
      'Design tools (Figma, Adobe Creative Suite)',
      'Content creation and copywriting',
      'Video and multimedia production',
      'Brand and visual identity',
    ],
    exampleJobs: [
      'Graphic Designer',
      'UX/UI Designer',
      'Content Creator',
      'Video Producer',
      'Art Director',
      'Copywriter',
    ],
    resources: [
      { title: 'Skillshare', url: 'https://www.skillshare.com/' },
      { title: 'Dribbble Learn', url: 'https://dribbble.com/learn' },
      { title: 'Interaction Design Foundation', url: 'https://www.interaction-design.org/' },
    ],
  },
  {
    id: 'marketing_sales',
    title: 'Marketing, Sales & Communication',
    description:
      'Drive growth through customer acquisition, brand building, and persuasive communication. Ideal for outgoing individuals who enjoy connecting with people and driving results.',
    icon: '📣',
    weights: {
      technical_skills: { high: 0.6, medium: 1.0, low: 1.2 },
      creative_skills: { high: 1.5, medium: 1.2, low: 0.6 },
      communication_skills: { high: 2.0, medium: 1.2, low: 0.3 },
      enjoyed_skills: {
        presenting: 1.8,
        writing: 1.5,
        negotiation: 1.8,
        collaboration: 1.3,
        data_analysis: 1.0,
      },
      work_energizes: {
        connecting: 2.0,
        creating: 1.5,
        strategizing: 1.5,
        analyzing: 1.0,
      },
      problem_type: {
        business: 1.8,
        creative: 1.5,
        people: 1.5,
        analytical: 1.0,
        technical: 0.4,
      },
      industry_interest: {
        marketing_sales: 2.0,
        creative_media_design: 1.2,
        business_management: 1.0,
      },
      work_environment: {
        agency: 1.8,
        startup: 1.5,
        corporate: 1.2,
        freelance: 1.3,
        consulting: 1.0,
        nonprofit: 0.8,
      },
      team_size: {
        small: 1.5,
        medium: 1.5,
        large: 1.0,
        solo: 0.8,
      },
      structure_preference: { low: 1.2, medium: 1.3, high: 0.8 },
    },
    suggestedSkills: [
      'Digital marketing (SEO, SEM, social media)',
      'Sales and negotiation',
      'Content marketing and copywriting',
      'Marketing analytics',
      'Brand strategy and positioning',
    ],
    exampleJobs: [
      'Digital Marketer',
      'Sales Executive',
      'PR Manager',
      'Growth Strategist',
      'Brand Manager',
      'Account Executive',
    ],
    resources: [
      { title: 'HubSpot Academy', url: 'https://academy.hubspot.com/' },
      { title: 'Google Digital Garage', url: 'https://learndigital.withgoogle.com/' },
      { title: 'Salesforce Trailhead', url: 'https://trailhead.salesforce.com/' },
    ],
  },
  {
    id: 'law_government',
    title: 'Law, Government & Public Services',
    description:
      'Uphold justice, shape policy, and serve the public interest. Perfect for analytical minds with strong ethics who want to make a societal impact.',
    icon: '⚖️',
    weights: {
      technical_skills: { high: 0.8, medium: 1.0, low: 1.0 },
      creative_skills: { high: 0.6, medium: 0.8, low: 1.0 },
      communication_skills: { high: 2.0, medium: 1.2, low: 0.4 },
      enjoyed_skills: {
        writing: 2.0,
        research: 1.8,
        presenting: 1.5,
        negotiation: 1.5,
        problem_solving: 1.2,
      },
      work_energizes: {
        helping: 1.8,
        strategizing: 1.5,
        analyzing: 1.3,
        connecting: 1.0,
      },
      problem_type: {
        people: 1.8,
        analytical: 1.5,
        business: 1.2,
        creative: 0.5,
        technical: 0.4,
      },
      industry_interest: {
        law_government: 2.0,
        social_impact_nonprofit: 1.5,
        finance_accounting: 0.8,
      },
      work_environment: {
        corporate: 1.5,
        nonprofit: 1.5,
        consulting: 1.2,
        startup: 0.5,
        freelance: 0.8,
        agency: 0.5,
      },
      team_size: {
        medium: 1.5,
        small: 1.3,
        large: 1.2,
        solo: 0.8,
      },
      structure_preference: { low: 0.4, medium: 1.0, high: 2.0 },
    },
    suggestedSkills: [
      'Legal research and writing',
      'Policy analysis',
      'Public speaking and advocacy',
      'Regulatory compliance',
      'Negotiation and mediation',
    ],
    exampleJobs: [
      'Lawyer/Attorney',
      'Policy Analyst',
      'Civil Servant',
      'Diplomat',
      'Paralegal',
      'Legislative Aide',
    ],
    resources: [
      { title: 'Coursera Law Courses', url: 'https://www.coursera.org/browse/social-sciences/law' },
      { title: 'edX Government Courses', url: 'https://www.edx.org/learn/government' },
      { title: 'Khan Academy Civics', url: 'https://www.khanacademy.org/humanities/us-government-and-civics' },
    ],
  },
  {
    id: 'science_research',
    title: 'Science, Research & Data',
    description:
      'Advance knowledge through scientific discovery, data analysis, and research. Ideal for curious minds who love investigating questions and uncovering insights.',
    icon: '🔬',
    weights: {
      technical_skills: { high: 1.8, medium: 1.2, low: 0.5 },
      creative_skills: { high: 0.8, medium: 1.0, low: 0.8 },
      communication_skills: { high: 1.0, medium: 1.0, low: 0.8 },
      enjoyed_skills: {
        research: 2.0,
        data_analysis: 2.0,
        problem_solving: 1.5,
        writing: 1.2,
        coding: 1.0,
      },
      work_energizes: {
        analyzing: 2.0,
        learning: 2.0,
        building: 1.0,
        creating: 0.8,
      },
      problem_type: {
        analytical: 2.0,
        technical: 1.5,
        creative: 0.8,
        business: 0.5,
        people: 0.4,
      },
      industry_interest: {
        science_research: 2.0,
        technology_engineering: 1.2,
        healthcare_life_sciences: 1.2,
      },
      work_environment: {
        corporate: 1.2,
        nonprofit: 1.3,
        startup: 1.0,
        consulting: 1.0,
        freelance: 0.8,
        agency: 0.4,
      },
      team_size: {
        small: 1.8,
        solo: 1.5,
        medium: 1.0,
        large: 0.8,
      },
      structure_preference: { low: 1.0, medium: 1.5, high: 1.0 },
    },
    suggestedSkills: [
      'Research methodology and design',
      'Statistical analysis (R, Python, SPSS)',
      'Data visualization and reporting',
      'Scientific writing and publishing',
      'Machine learning and data science',
    ],
    exampleJobs: [
      'Research Scientist',
      'Data Scientist',
      'Lab Analyst',
      'Statistician',
      'Research Associate',
      'Data Analyst',
    ],
    resources: [
      { title: 'Kaggle', url: 'https://www.kaggle.com/' },
      { title: 'DataCamp', url: 'https://www.datacamp.com/' },
      { title: 'Coursera Data Science', url: 'https://www.coursera.org/browse/data-science' },
    ],
  },
  {
    id: 'manufacturing_construction',
    title: 'Manufacturing, Construction & Trades',
    description:
      'Build physical infrastructure and produce goods that shape the world. Perfect for hands-on problem solvers who enjoy tangible, visible results.',
    icon: '🏗️',
    weights: {
      technical_skills: { high: 1.8, medium: 1.5, low: 0.6 },
      creative_skills: { high: 1.0, medium: 1.0, low: 0.8 },
      communication_skills: { high: 1.0, medium: 1.0, low: 0.8 },
      enjoyed_skills: {
        problem_solving: 1.8,
        collaboration: 1.3,
        leadership: 1.2,
        design: 1.0,
        data_analysis: 0.8,
      },
      work_energizes: {
        building: 2.0,
        optimizing: 1.5,
        creating: 1.2,
        helping: 0.8,
      },
      problem_type: {
        technical: 2.0,
        analytical: 1.2,
        creative: 1.0,
        business: 0.8,
        people: 0.6,
      },
      industry_interest: {
        manufacturing_construction: 2.0,
        technology_engineering: 1.0,
        science_research: 0.6,
      },
      work_environment: {
        corporate: 1.3,
        startup: 1.0,
        freelance: 1.2,
        consulting: 0.8,
        nonprofit: 0.5,
        agency: 0.5,
      },
      team_size: {
        medium: 1.5,
        small: 1.3,
        large: 1.2,
        solo: 0.8,
      },
      structure_preference: { low: 0.6, medium: 1.2, high: 1.5 },
    },
    suggestedSkills: [
      'Engineering principles (civil, mechanical, electrical)',
      'Project management and planning',
      'CAD and technical drawing',
      'Safety compliance and regulations',
      'Quality control and assurance',
    ],
    exampleJobs: [
      'Civil Engineer',
      'Architect',
      'Electrician',
      'Construction Manager',
      'Surveyor',
      'Manufacturing Engineer',
    ],
    resources: [
      { title: 'Coursera Engineering', url: 'https://www.coursera.org/browse/physical-science-and-engineering' },
      { title: 'OSHA Training', url: 'https://www.osha.gov/training' },
      { title: 'SkillsUSA', url: 'https://www.skillsusa.org/' },
    ],
  },
  {
    id: 'hospitality_service',
    title: 'Hospitality, Travel & Service',
    description:
      'Create memorable experiences through exceptional service and event management. Ideal for personable individuals who thrive on making others happy.',
    icon: '🏨',
    weights: {
      technical_skills: { high: 0.5, medium: 0.8, low: 1.2 },
      creative_skills: { high: 1.2, medium: 1.2, low: 0.8 },
      communication_skills: { high: 2.0, medium: 1.2, low: 0.3 },
      enjoyed_skills: {
        collaboration: 1.8,
        presenting: 1.3,
        negotiation: 1.2,
        leadership: 1.2,
        problem_solving: 1.0,
      },
      work_energizes: {
        helping: 2.0,
        connecting: 2.0,
        creating: 1.0,
        optimizing: 1.0,
      },
      problem_type: {
        people: 2.0,
        creative: 1.2,
        business: 1.0,
        analytical: 0.5,
        technical: 0.3,
      },
      industry_interest: {
        hospitality_service: 2.0,
        marketing_sales: 1.0,
        social_impact_nonprofit: 0.8,
      },
      work_environment: {
        corporate: 1.2,
        startup: 1.0,
        freelance: 1.3,
        nonprofit: 0.8,
        agency: 1.2,
        consulting: 0.6,
      },
      team_size: {
        medium: 1.5,
        small: 1.3,
        large: 1.2,
        solo: 0.6,
      },
      structure_preference: { low: 1.0, medium: 1.5, high: 1.0 },
    },
    suggestedSkills: [
      'Customer service excellence',
      'Event planning and coordination',
      'Hospitality management systems',
      'Cultural awareness and languages',
      'Conflict resolution',
    ],
    exampleJobs: [
      'Hotel Manager',
      'Event Planner',
      'Travel Consultant',
      'Customer Success Manager',
      'Restaurant Manager',
      'Concierge',
    ],
    resources: [
      { title: 'Cornell Hospitality', url: 'https://online.cornell.edu/hospitality' },
      { title: 'Coursera Hospitality', url: 'https://www.coursera.org/browse/business/marketing' },
      { title: 'American Hotel & Lodging Association', url: 'https://www.ahla.com/' },
    ],
  },
  {
    id: 'social_impact_nonprofit',
    title: 'Social Impact, Non-Profit & Community',
    description:
      'Drive positive change through community development, advocacy, and mission-driven work. Perfect for purpose-driven individuals who want to make a difference.',
    icon: '🌍',
    weights: {
      technical_skills: { high: 0.6, medium: 0.8, low: 1.0 },
      creative_skills: { high: 1.2, medium: 1.0, low: 0.8 },
      communication_skills: { high: 2.0, medium: 1.2, low: 0.4 },
      enjoyed_skills: {
        collaboration: 1.8,
        presenting: 1.5,
        writing: 1.5,
        leadership: 1.5,
        negotiation: 1.2,
        research: 1.0,
      },
      work_energizes: {
        helping: 2.0,
        connecting: 1.8,
        strategizing: 1.2,
        creating: 1.0,
      },
      problem_type: {
        people: 2.0,
        business: 1.2,
        creative: 1.0,
        analytical: 0.8,
        technical: 0.4,
      },
      industry_interest: {
        social_impact_nonprofit: 2.0,
        education_training: 1.2,
        healthcare_life_sciences: 1.0,
      },
      work_environment: {
        nonprofit: 2.0,
        consulting: 1.0,
        corporate: 0.6,
        startup: 1.0,
        freelance: 0.8,
        agency: 0.6,
      },
      team_size: {
        small: 1.8,
        medium: 1.3,
        solo: 1.0,
        large: 0.8,
      },
      structure_preference: { low: 1.2, medium: 1.3, high: 0.8 },
    },
    suggestedSkills: [
      'Program management and evaluation',
      'Fundraising and grant writing',
      'Community engagement',
      'Advocacy and public policy',
      'Impact measurement',
    ],
    exampleJobs: [
      'NGO Program Manager',
      'Social Worker',
      'Nonprofit Director',
      'Community Organizer',
      'Fundraising Manager',
      'Volunteer Coordinator',
    ],
    resources: [
      { title: 'Idealist', url: 'https://www.idealist.org/' },
      { title: 'Nonprofit Ready', url: 'https://www.nonprofitready.org/' },
      { title: 'Foundation Center', url: 'https://candid.org/' },
    ],
  },
  {
    id: 'beauty_fashion',
    title: 'Beauty, Fashion & Lifestyle',
    description:
      'Shape trends and help people express themselves through fashion, beauty, and personal style. Ideal for creative individuals with an eye for aesthetics and passion for self-expression.',
    icon: '👗',
    weights: {
      technical_skills: { high: 0.6, medium: 0.8, low: 1.0 },
      creative_skills: { high: 2.0, medium: 1.2, low: 0.4 },
      communication_skills: { high: 1.5, medium: 1.2, low: 0.6 },
      enjoyed_skills: {
        design: 2.0,
        presenting: 1.5,
        collaboration: 1.3,
        negotiation: 1.2,
        writing: 1.0,
      },
      work_energizes: {
        creating: 2.0,
        connecting: 1.8,
        helping: 1.5,
        building: 1.0,
      },
      problem_type: {
        creative: 2.0,
        people: 1.5,
        business: 1.2,
        analytical: 0.5,
        technical: 0.3,
      },
      industry_interest: {
        beauty_fashion: 2.0,
        creative_media_design: 1.5,
        marketing_sales: 1.2,
      },
      work_environment: {
        agency: 1.8,
        freelance: 1.8,
        startup: 1.3,
        corporate: 1.0,
        consulting: 0.8,
        nonprofit: 0.5,
      },
      team_size: {
        small: 1.8,
        solo: 1.5,
        medium: 1.0,
        large: 0.6,
      },
      structure_preference: { low: 1.8, medium: 1.0, high: 0.4 },
    },
    suggestedSkills: [
      'Fashion design and styling',
      'Beauty techniques and trends',
      'Visual merchandising',
      'Brand development',
      'Client consultation',
    ],
    exampleJobs: [
      'Fashion Designer',
      'Stylist',
      'Makeup Artist',
      'Brand Buyer',
      'Beauty Consultant',
      'Fashion Photographer',
    ],
    resources: [
      { title: 'Business of Fashion', url: 'https://www.businessoffashion.com/' },
      { title: 'Skillshare Fashion', url: 'https://www.skillshare.com/browse/fashion' },
      { title: 'Vogue Business', url: 'https://www.voguebusiness.com/' },
    ],
  },
];

export function getCareerById(id: string): CareerPath | undefined {
  return careerPaths.find((career) => career.id === id);
}
