import { Question } from './types';

export const questions: Question[] = [
  // Experience Questions
  {
    id: 'years_experience',
    category: 'experience',
    type: 'slider',
    question: 'How many years of professional experience do you have?',
    description: 'Include all relevant work experience, internships, and freelance work.',
    min: 0,
    max: 20,
    step: 1,
    minLabel: '0 years',
    maxLabel: '20+ years',
    required: true,
  },
  {
    id: 'industries',
    category: 'experience',
    type: 'multi-select',
    question: 'Which industries have you worked in?',
    description: 'Select all that apply.',
    options: [
      { value: 'technology_engineering', label: 'Technology & Engineering' },
      { value: 'business_management', label: 'Business & Management' },
      { value: 'finance_accounting', label: 'Finance & Accounting' },
      { value: 'healthcare_life_sciences', label: 'Healthcare & Life Sciences' },
      { value: 'education_training', label: 'Education & Training' },
      { value: 'creative_media_design', label: 'Creative, Media & Design' },
      { value: 'marketing_sales', label: 'Marketing & Sales' },
      { value: 'law_government', label: 'Law & Government' },
      { value: 'science_research', label: 'Science & Research' },
      { value: 'manufacturing_construction', label: 'Manufacturing & Construction' },
      { value: 'hospitality_service', label: 'Hospitality & Service' },
      { value: 'social_impact_nonprofit', label: 'Social Impact & Non-Profit' },
      { value: 'beauty_fashion', label: 'Beauty, Fashion & Lifestyle' },
      { value: 'other', label: 'Other (Sports, Entertainment, Agriculture, etc.)' },
      { value: 'none', label: 'No professional experience yet' },
    ],
    required: true,
  },
  {
    id: 'education',
    category: 'experience',
    type: 'multiple-choice',
    question: 'What is your highest level of education?',
    options: [
      { value: 'high_school', label: 'High School' },
      { value: 'some_college', label: 'Some College' },
      { value: 'bachelors', label: "Bachelor's Degree" },
      { value: 'masters', label: "Master's Degree" },
      { value: 'phd', label: 'PhD / Doctorate' },
      { value: 'bootcamp', label: 'Bootcamp / Certification' },
    ],
    required: true,
  },

  // Skills Questions
  {
    id: 'technical_skills',
    category: 'skills',
    type: 'slider',
    question: 'How would you rate your technical/analytical skills?',
    description: 'Including coding, data analysis, mathematics, or engineering.',
    min: 1,
    max: 10,
    step: 1,
    minLabel: 'Beginner',
    maxLabel: 'Expert',
    required: true,
  },
  {
    id: 'communication_skills',
    category: 'skills',
    type: 'slider',
    question: 'How would you rate your communication skills?',
    description: 'Including writing, presenting, and interpersonal communication.',
    min: 1,
    max: 10,
    step: 1,
    minLabel: 'Developing',
    maxLabel: 'Excellent',
    required: true,
  },
  {
    id: 'creative_skills',
    category: 'skills',
    type: 'slider',
    question: 'How would you rate your creative/design skills?',
    description: 'Including visual design, writing, problem-solving creativity.',
    min: 1,
    max: 10,
    step: 1,
    minLabel: 'Developing',
    maxLabel: 'Excellent',
    required: true,
  },
  {
    id: 'enjoyed_skills',
    category: 'skills',
    type: 'multi-select',
    question: 'Which skills do you most enjoy using at work?',
    description: 'Select up to 4 that you find most fulfilling.',
    options: [
      { value: 'problem_solving', label: 'Problem Solving' },
      { value: 'data_analysis', label: 'Data Analysis' },
      { value: 'writing', label: 'Writing & Documentation' },
      { value: 'presenting', label: 'Presenting & Public Speaking' },
      { value: 'design', label: 'Design & Visual Work' },
      { value: 'coding', label: 'Coding & Technical Work' },
      { value: 'leadership', label: 'Leadership & Management' },
      { value: 'negotiation', label: 'Negotiation & Sales' },
      { value: 'research', label: 'Research & Investigation' },
      { value: 'collaboration', label: 'Team Collaboration' },
    ],
    required: true,
  },

  // Interests Questions
  {
    id: 'work_energizes',
    category: 'interests',
    type: 'multi-select',
    question: 'What type of work energizes you the most?',
    description: 'Select all that apply.',
    options: [
      { value: 'building', label: 'Building things from scratch' },
      { value: 'optimizing', label: 'Optimizing existing processes' },
      { value: 'helping', label: 'Helping and mentoring others' },
      { value: 'analyzing', label: 'Analyzing data and patterns' },
      { value: 'creating', label: 'Creating visual or written content' },
      { value: 'strategizing', label: 'Developing strategies and plans' },
      { value: 'connecting', label: 'Connecting with clients/customers' },
      { value: 'learning', label: 'Learning new technologies/methods' },
    ],
    required: true,
  },
  {
    id: 'problem_type',
    category: 'interests',
    type: 'multiple-choice',
    question: 'What type of problems do you prefer solving?',
    options: [
      { value: 'technical', label: 'Technical challenges (bugs, systems, architecture)' },
      { value: 'people', label: 'People challenges (team dynamics, communication)' },
      { value: 'business', label: 'Business challenges (growth, strategy, revenue)' },
      { value: 'creative', label: 'Creative challenges (design, user experience)' },
      { value: 'analytical', label: 'Analytical challenges (data, research, insights)' },
    ],
    required: true,
  },
  {
    id: 'industry_interest',
    category: 'interests',
    type: 'multiple-choice',
    question: 'Which industry area interests you most?',
    options: [
      { value: 'technology_engineering', label: 'Technology & Engineering' },
      { value: 'business_management', label: 'Business, Management & Strategy' },
      { value: 'finance_accounting', label: 'Finance & Accounting' },
      { value: 'healthcare_life_sciences', label: 'Healthcare & Life Sciences' },
      { value: 'education_training', label: 'Education & Training' },
      { value: 'creative_media_design', label: 'Creative, Media & Design' },
      { value: 'marketing_sales', label: 'Marketing, Sales & Communication' },
      { value: 'law_government', label: 'Law, Government & Public Services' },
      { value: 'science_research', label: 'Science, Research & Data' },
      { value: 'manufacturing_construction', label: 'Manufacturing, Construction & Trades' },
      { value: 'hospitality_service', label: 'Hospitality, Travel & Service' },
      { value: 'social_impact_nonprofit', label: 'Social Impact, Non-Profit & Community' },
      { value: 'beauty_fashion', label: 'Beauty, Fashion & Lifestyle' },
      { value: 'other', label: 'Other (Sports, Entertainment, Agriculture, etc.)' },
    ],
    required: true,
  },

  // Preferences Questions
  {
    id: 'work_environment',
    category: 'preferences',
    type: 'multiple-choice',
    question: 'What is your ideal work environment?',
    options: [
      { value: 'startup', label: 'Fast-paced startup' },
      { value: 'corporate', label: 'Established corporation' },
      { value: 'agency', label: 'Creative agency' },
      { value: 'consulting', label: 'Consulting firm' },
      { value: 'freelance', label: 'Freelance/Independent' },
      { value: 'nonprofit', label: 'Non-profit organization' },
    ],
    required: true,
  },
  {
    id: 'team_size',
    category: 'preferences',
    type: 'multiple-choice',
    question: 'What team size do you prefer working in?',
    options: [
      { value: 'solo', label: 'Solo / Independent work' },
      { value: 'small', label: 'Small team (2-5 people)' },
      { value: 'medium', label: 'Medium team (6-15 people)' },
      { value: 'large', label: 'Large team (15+ people)' },
    ],
    required: true,
  },
  {
    id: 'structure_preference',
    category: 'preferences',
    type: 'slider',
    question: 'How much structure do you prefer in your work?',
    description: 'From flexible and autonomous to well-defined and structured.',
    min: 1,
    max: 10,
    step: 1,
    minLabel: 'Flexible',
    maxLabel: 'Structured',
    required: true,
  },
  {
    id: 'remote_preference',
    category: 'preferences',
    type: 'multiple-choice',
    question: 'What is your preferred work arrangement?',
    options: [
      { value: 'remote', label: 'Fully remote' },
      { value: 'hybrid', label: 'Hybrid (mix of office and remote)' },
      { value: 'office', label: 'In-office' },
      { value: 'flexible', label: 'No strong preference' },
    ],
    required: false,
  },

  // Goals Questions
  {
    id: 'salary_importance',
    category: 'goals',
    type: 'slider',
    question: 'How important is salary/compensation to you?',
    min: 1,
    max: 10,
    step: 1,
    minLabel: 'Less important',
    maxLabel: 'Very important',
    required: true,
  },
  {
    id: 'work_life_balance',
    category: 'goals',
    type: 'slider',
    question: 'How important is work-life balance to you?',
    min: 1,
    max: 10,
    step: 1,
    minLabel: 'Less important',
    maxLabel: 'Very important',
    required: true,
  },
  {
    id: 'growth_importance',
    category: 'goals',
    type: 'slider',
    question: 'How important is career growth and learning?',
    min: 1,
    max: 10,
    step: 1,
    minLabel: 'Less important',
    maxLabel: 'Very important',
    required: true,
  },
  {
    id: 'impact_importance',
    category: 'goals',
    type: 'slider',
    question: 'How important is making a meaningful impact?',
    description: 'Whether on users, society, or the company.',
    min: 1,
    max: 10,
    step: 1,
    minLabel: 'Less important',
    maxLabel: 'Very important',
    required: true,
  },
];

export const questionCategories = [
  { id: 'experience', title: 'Experience', icon: '/images/ex.png' },
  { id: 'skills', title: 'Skills', icon: '/images/skills.png' },
  { id: 'interests', title: 'Interests', icon: '/images/pre.png' },
  { id: 'preferences', title: 'Preferences', icon: '/images/pre.png' },
  { id: 'goals', title: 'Goals', icon: '/images/goal.png' },
] as const;

export function getQuestionsByCategory(category: string): Question[] {
  return questions.filter((q) => q.category === category);
}

export function getTotalQuestions(): number {
  return questions.length;
}
